
services:
  ritl:
    build: .
    container_name: ritl
    volumes:
      - .:/app
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHONUNBUFFERED=1
