services:
  ritl:
    image: krissal1234/rocket-in-the-loop:v1.0.0
    container_name: ritl
    ports:
      - "50101:50101"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - ritl-net

networks:
  ritl-net:
    driver: bridge